"""Public facade for the Nullsec Trader Tool.

This module has one narrow responsibility: provide the stable top-level import
surface used by tests and local tooling, and delegate CLI execution to
`runtime_runner.run_cli()`.

It intentionally contains no business logic.
"""

from __future__ import annotations

import candidate_engine as _candidate_engine
import character_profile as _character_profile
import confidence_calibration as _confidence_calibration
import config_loader as _config_loader
import eve_character_client as _eve_character_client
import eve_sso as _eve_sso
import execution_plan as _execution_plan
import explainability as _explainability
import fees as _fees
import journal_cli as _journal_cli
import journal_models as _journal_models
import journal_reconciliation as _journal_reconciliation
import journal_reporting as _journal_reporting
import journal_store as _journal_store
import local_cache as _local_cache
import location_utils as _location_utils
import market_fetch as _market_fetch
import market_normalization as _market_normalization
import market_plausibility as _market_plausibility
import models as _models
import portfolio_builder as _portfolio_builder
import route_search as _route_search
import runtime_clients as _runtime_clients
import runtime_common as _runtime_common
import runtime_reports as _runtime_reports
import runtime_runner as _runtime_runner
import scoring as _scoring
import shipping as _shipping
import startup_helpers as _startup_helpers


_EXPORTS = {
    "_choose_best_route_wide_candidate": _candidate_engine._choose_best_route_wide_candidate,
    "_route_adjusted_candidate_score": _candidate_engine._route_adjusted_candidate_score,
    "apply_strategy_filters": _candidate_engine.apply_strategy_filters,
    "build_levels": _candidate_engine.build_levels,
    "compute_candidates": _candidate_engine.compute_candidates,
    "compute_route_wide_candidates_for_source": _candidate_engine.compute_route_wide_candidates_for_source,
    "depth_slice": _candidate_engine.depth_slice,
    "get_structure_micro_liquidity": _candidate_engine.get_structure_micro_liquidity,
    "DEFAULT_CHARACTER_CONTEXT_CFG": _character_profile.DEFAULT_CHARACTER_CONTEXT_CFG,
    "apply_character_fee_overrides": _character_profile.apply_character_fee_overrides,
    "attach_character_context_to_result": _character_profile.attach_character_context_to_result,
    "build_character_context_summary": _character_profile.build_character_context_summary,
    "build_character_profile": _character_profile.build_character_profile,
    "character_status_lines": _character_profile.character_status_lines,
    "requested_character_scopes": _character_profile.requested_character_scopes,
    "resolve_character_context": _character_profile.resolve_character_context,
    "resolve_character_context_cfg": _character_profile.resolve_character_context_cfg,
    "sync_character_profile": _character_profile.sync_character_profile,
    "CONFIDENCE_DEFINITIONS": _confidence_calibration.CONFIDENCE_DEFINITIONS,
    "CONFIDENCE_DIMENSIONS": _confidence_calibration.CONFIDENCE_DIMENSIONS,
    "DEFAULT_CONFIDENCE_BUCKETS": _confidence_calibration.DEFAULT_CONFIDENCE_BUCKETS,
    "apply_calibration_to_record": _confidence_calibration.apply_calibration_to_record,
    "build_confidence_calibration": _confidence_calibration.build_confidence_calibration,
    "calibrate_confidence_value": _confidence_calibration.calibrate_confidence_value,
    "classify_trade_outcome": _confidence_calibration.classify_trade_outcome,
    "format_confidence_calibration_report": _confidence_calibration.format_confidence_calibration_report,
    "overall_raw_confidence_from_components": _confidence_calibration.overall_raw_confidence_from_components,
    "resolve_confidence_calibration_cfg": _confidence_calibration.resolve_confidence_calibration_cfg,
    "transport_confidence_to_score": _confidence_calibration.transport_confidence_to_score,
    "INTERNAL_REASON_CODES": _explainability.INTERNAL_REASON_CODES,
    "REASON_CATALOG": _explainability.REASON_CATALOG,
    "build_candidate_explainability": _explainability.build_candidate_explainability,
    "build_pick_score_breakdown": _explainability.build_pick_score_breakdown,
    "build_reason_entry": _explainability.build_reason_entry,
    "build_rejected_candidate_table": _explainability.build_rejected_candidate_table,
    "build_route_explainability": _explainability.build_route_explainability,
    "ensure_record_explainability": _explainability.ensure_record_explainability,
    "format_reason_digest": _explainability.format_reason_digest,
    "normalize_reason_entry": _explainability.normalize_reason_entry,
    "reason_code_for_internal_reason": _explainability.reason_code_for_internal_reason,
    "_build_fix_hint": _config_loader._build_fix_hint,
    "_collect_required_structure_ids": _config_loader._collect_required_structure_ids,
    "_prepare_trade_filters": _config_loader._prepare_trade_filters,
    "_resolve_strict_mode_cfg": _config_loader._resolve_strict_mode_cfg,
    "_resolve_structure_region_map": _config_loader._resolve_structure_region_map,
    "_validate_structure_region_mapping": _config_loader._validate_structure_region_mapping,
    "ensure_dirs": _config_loader.ensure_dirs,
    "fail_on_invalid_config": _config_loader.fail_on_invalid_config,
    "load_config": _config_loader.load_config,
    "load_json": _config_loader.load_json,
    "save_json": _config_loader.save_json,
    "validate_config": _config_loader.validate_config,
    "CharacterESIError": _eve_character_client.CharacterESIError,
    "EveCharacterClient": _eve_character_client.EveCharacterClient,
    "DEFAULT_AUTHORIZATION_ENDPOINT": _eve_sso.DEFAULT_AUTHORIZATION_ENDPOINT,
    "DEFAULT_SSO_METADATA_URL": _eve_sso.DEFAULT_SSO_METADATA_URL,
    "DEFAULT_TOKEN_ENDPOINT": _eve_sso.DEFAULT_TOKEN_ENDPOINT,
    "EveSSOAuth": _eve_sso.EveSSOAuth,
    "SSOAuthError": _eve_sso.SSOAuthError,
    "decode_access_token_claims": _eve_sso.decode_access_token_claims,
    "requested_sso_scopes": _eve_sso.normalize_scopes,
    "token_identity_from_claims": _eve_sso.token_identity_from_claims,
    "write_execution_plan_profiles": _execution_plan.write_execution_plan_profiles,
    "write_route_leaderboard": _execution_plan.write_route_leaderboard,
    "compute_trade_financials": _fees.compute_trade_financials,
    "JOURNAL_ALLOWED_STATUSES": _journal_models.JOURNAL_ALLOWED_STATUSES,
    "JOURNAL_CLOSED_STATUSES": _journal_models.JOURNAL_CLOSED_STATUSES,
    "JOURNAL_OPEN_STATUSES": _journal_models.JOURNAL_OPEN_STATUSES,
    "attach_plan_metadata": _journal_models.attach_plan_metadata,
    "build_trade_plan_manifest": _journal_models.build_trade_plan_manifest,
    "compute_actual_days_to_sell": _journal_models.compute_actual_days_to_sell,
    "compute_realized_outcome_score": _journal_models.compute_realized_outcome_score,
    "entry_profit_delta": _journal_models.entry_profit_delta,
    "make_run_id": _journal_models.make_run_id,
    "normalize_journal_timestamp": _journal_models.normalize_journal_timestamp,
    "utc_now_iso": _journal_models.utc_now_iso,
    "MATCH_THRESHOLD": _journal_reconciliation.MATCH_THRESHOLD,
    "AMBIGUOUS_MARGIN": _journal_reconciliation.AMBIGUOUS_MARGIN,
    "reconcile_wallet_snapshot": _journal_reconciliation.reconcile_wallet_snapshot,
    "build_journal_report": _journal_reporting.build_journal_report,
    "enrich_journal_entry": _journal_reporting.enrich_journal_entry,
    "format_closed_positions": _journal_reporting.format_closed_positions,
    "format_journal_overview": _journal_reporting.format_journal_overview,
    "format_journal_report": _journal_reporting.format_journal_report,
    "format_open_positions": _journal_reporting.format_open_positions,
    "format_personal_trade_history": _journal_reporting.format_personal_trade_history,
    "format_reconciliation_overview": _journal_reporting.format_reconciliation_overview,
    "format_unmatched_wallet_activity": _journal_reporting.format_unmatched_wallet_activity,
    "summarize_journal": _journal_reporting.summarize_journal,
    "DEFAULT_JOURNAL_DB_PATH": _journal_store.DEFAULT_JOURNAL_DB_PATH,
    "fetch_closed_journal_entries": _journal_store.fetch_closed_journal_entries,
    "fetch_journal_entries": _journal_store.fetch_journal_entries,
    "fetch_journal_entry": _journal_store.fetch_journal_entry,
    "fetch_journal_events": _journal_store.fetch_journal_events,
    "fetch_open_journal_entries": _journal_store.fetch_open_journal_entries,
    "import_trade_plan_into_journal": _journal_store.import_trade_plan_into_journal,
    "initialize_journal_db": _journal_store.initialize_journal_db,
    "load_trade_plan_manifest": _journal_store.load_trade_plan_manifest,
    "reconcile_journal_with_character_context": _journal_store.reconcile_journal_with_character_context,
    "reconcile_journal_with_wallet": _journal_store.reconcile_journal_with_wallet,
    "record_journal_buy": _journal_store.record_journal_buy,
    "record_journal_sell": _journal_store.record_journal_sell,
    "resolve_journal_db_path": _journal_store.resolve_journal_db_path,
    "update_journal_entry_status": _journal_store.update_journal_entry_status,
    "cache_record_age_sec": _local_cache.cache_record_age_sec,
    "cached_payload": _local_cache.cached_payload,
    "is_cache_fresh": _local_cache.is_cache_fresh,
    "load_cache_record": _local_cache.load_cache_record,
    "save_cache_record": _local_cache.save_cache_record,
    "run_journal_cli": _journal_cli.run_journal_cli,
    "label_to_slug": _location_utils.label_to_slug,
    "normalize_location_label": _location_utils.normalize_location_label,
    "_fetch_orders_for_node": _market_fetch._fetch_orders_for_node,
    "make_snapshot_payload": _market_normalization.make_snapshot_payload,
    "normalize_replay_snapshot": _market_normalization.normalize_replay_snapshot,
    "DEFAULT_MARKET_PLAUSIBILITY_CFG": _market_plausibility.DEFAULT_MARKET_PLAUSIBILITY_CFG,
    "assess_market_plausibility": _market_plausibility.assess_market_plausibility,
    "depth_decay": _market_plausibility.depth_decay,
    "effective_spread_after_depth": _market_plausibility.effective_spread_after_depth,
    "order_concentration_ratio": _market_plausibility.order_concentration_ratio,
    "price_gap_after_top_levels": _market_plausibility.price_gap_after_top_levels,
    "reference_price_deviation": _market_plausibility.reference_price_deviation,
    "resolve_market_plausibility_cfg": _market_plausibility.resolve_market_plausibility_cfg,
    "top_of_book_volume_ratio": _market_plausibility.top_of_book_volume_ratio,
    "usable_depth_at_confidence_price": _market_plausibility.usable_depth_at_confidence_price,
    "weighted_price_for_units": _market_plausibility.weighted_price_for_units,
    "FilterFunnel": _models.FilterFunnel,
    "OrderLevel": _models.OrderLevel,
    "TradeCandidate": _models.TradeCandidate,
    "_sort_candidates_for_cargo_fill": _portfolio_builder._sort_candidates_for_cargo_fill,
    "build_portfolio": _portfolio_builder.build_portfolio,
    "choose_portfolio_for_route": _portfolio_builder.choose_portfolio_for_route,
    "local_search_optimize": _portfolio_builder.local_search_optimize,
    "portfolio_stats": _portfolio_builder.portfolio_stats,
    "sort_picks_for_output": _portfolio_builder.sort_picks_for_output,
    "try_cargo_fill": _portfolio_builder.try_cargo_fill,
    "validate_portfolio": _portfolio_builder.validate_portfolio,
    "_parse_route_pair_token": _route_search._parse_route_pair_token,
    "_resolve_allowed_route_pair_lane_overrides": _route_search._resolve_allowed_route_pair_lane_overrides,
    "_resolve_allowed_route_pairs": _route_search._resolve_allowed_route_pairs,
    "_resolve_route_search_cfg": _route_search._resolve_route_search_cfg,
    "build_route_search_profiles": _route_search.build_route_search_profiles,
    "route_ranking_value": _route_search.route_ranking_value,
    "summarize_route_for_ranking": _route_search.summarize_route_for_ranking,
    "CallbackState": _runtime_clients.CallbackState,
    "CachedResponse": _runtime_clients.CachedResponse,
    "ESIClient": _runtime_clients.ESIClient,
    "OAuthHandler": _runtime_clients.OAuthHandler,
    "ReplayESIClient": _runtime_clients.ReplayESIClient,
    "BASE_DIR": _runtime_common.BASE_DIR,
    "CACHE_DIR": _runtime_common.CACHE_DIR,
    "CONFIG_PATH": _runtime_common.CONFIG_PATH,
    "HTTP_CACHE_PATH": _runtime_common.HTTP_CACHE_PATH,
    "JOURNAL_DB_PATH": _runtime_common.JOURNAL_DB_PATH,
    "TOKEN_PATH": _runtime_common.TOKEN_PATH,
    "TYPE_CACHE_PATH": _runtime_common.TYPE_CACHE_PATH,
    "_has_live_esi_credentials": _runtime_common._has_live_esi_credentials,
    "b64url": _runtime_common.b64url,
    "die": _runtime_common.die,
    "input_with_default": _runtime_common.input_with_default,
    "make_basic_auth": _runtime_common.make_basic_auth,
    "parse_cli_args": _runtime_common.parse_cli_args,
    "parse_isk": _runtime_common.parse_isk,
    "fmt_isk": _runtime_reports.fmt_isk,
    "pick_total_fees_taxes": _runtime_reports.pick_total_fees_taxes,
    "write_chain_summary": _runtime_reports.write_chain_summary,
    "write_csv": _runtime_reports.write_csv,
    "write_enhanced_summary": _runtime_reports.write_enhanced_summary,
    "write_execution_plan_chain": _runtime_reports.write_execution_plan_chain,
    "write_top_candidate_dump": _runtime_reports.write_top_candidate_dump,
    "_apply_capital_flow_to_leg": _runtime_runner._apply_capital_flow_to_leg,
    "_compute_chain_leg_budget": _runtime_runner._compute_chain_leg_budget,
    "_resolve_budget_split_cfg": _runtime_runner._resolve_budget_split_cfg,
    "_resolve_capital_flow_cfg": _runtime_runner._resolve_capital_flow_cfg,
    "_resolve_route_profiles_cfg": _runtime_runner._resolve_route_profiles_cfg,
    "_resolve_route_wide_scan_cfg": _runtime_runner._resolve_route_wide_scan_cfg,
    "build_adjacent_pairs": _runtime_runner.build_adjacent_pairs,
    "build_route_profiles": _runtime_runner.build_route_profiles,
    "build_route_wide_pairs": _runtime_runner.build_route_wide_pairs,
    "enforce_route_destination": _runtime_runner.enforce_route_destination,
    "evaluate_leg_disabled": _runtime_runner.evaluate_leg_disabled,
    "main": _runtime_runner.main,
    "run_cli": _runtime_runner.run_cli,
    "make_skipped_chain_leg": _runtime_runner.make_skipped_chain_leg,
    "run_route": _runtime_runner.run_route,
    "run_route_wide_leg": _runtime_runner.run_route_wide_leg,
    "run_snapshot_only": _runtime_runner.run_snapshot_only,
    "apply_strategy_mode": _scoring.apply_strategy_mode,
    "compute_volatility_score": _scoring.compute_volatility_score,
    "_extract_shipping_lane_params": _shipping._extract_shipping_lane_params,
    "_lane_has_complete_pricing_params": _shipping._lane_has_complete_pricing_params,
    "_lane_provider_from_cfg": _shipping._lane_provider_from_cfg,
    "_match_shipping_lanes": _shipping._match_shipping_lanes,
    "_pick_passes_profit_floors": _shipping._pick_passes_profit_floors,
    "_policy_provider_for_route": _shipping._policy_provider_for_route,
    "apply_route_costs_and_prune": _shipping.apply_route_costs_and_prune,
    "apply_route_costs_to_picks": _shipping.apply_route_costs_to_picks,
    "build_jita_split_price_map": _shipping.build_jita_split_price_map,
    "build_route_context": _shipping.build_route_context,
    "compute_jita_split_price": _shipping.compute_jita_split_price,
    "compute_shipping_lane_reward_cost": _shipping.compute_shipping_lane_reward_cost,
    "compute_shipping_lane_reward_cost_single": _shipping.compute_shipping_lane_reward_cost_single,
    "compute_shipping_lane_total_cost": _shipping.compute_shipping_lane_total_cost,
    "resolve_route_cost_cfg": _shipping.resolve_route_cost_cfg,
    "resolve_shipping_lane_cfg": _shipping.resolve_shipping_lane_cfg,
    "split_shipping_contracts": _shipping.split_shipping_contracts,
    "_build_structure_context": _startup_helpers._build_structure_context,
    "_node_source_dest_info": _startup_helpers._node_source_dest_info,
    "_normalize_route_mode": _startup_helpers._normalize_route_mode,
    "_resolve_chain_runtime": _startup_helpers._resolve_chain_runtime,
    "_resolve_location_nodes": _startup_helpers._resolve_location_nodes,
    "_resolve_node_catalog": _startup_helpers._resolve_node_catalog,
    "_resolve_primary_structure_ids": _startup_helpers._resolve_primary_structure_ids,
}

globals().update(_EXPORTS)

__all__ = list(_EXPORTS.keys())


if __name__ == "__main__":
    _runtime_runner.run_cli()
